name: Using env imported from secret
# You can use secret environment settings from settings -> secrets -> actions and create secret variables
on:
  push:
    branches:
      - main
      - dev
jobs:
  print-my-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Show my secret
        run: |
          echo "My MONGODB_USERNAME is ${{ secrets.MONGODB_USERNAME }}"
  