name: Using env imported from secret
on:
  push:
    branches:
      - main
      - dev
# Adding environment variables
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  print-my-secret:
    steps:
      - name: Show my secret
        run: |
          "echo ${{ secrets.MONGODB_USERNAME }}"
  